language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
